set(_CATKIN_CURRENT_PACKAGE "commands_pilot")
set(commands_pilot_VERSION "0.0.0")
set(commands_pilot_MAINTAINER "alberto <alberto@todo.todo>")
set(commands_pilot_PACKAGE_FORMAT "2")
set(commands_pilot_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(commands_pilot_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(commands_pilot_BUILDTOOL_DEPENDS "catkin")
set(commands_pilot_BUILDTOOL_EXPORT_DEPENDS )
set(commands_pilot_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(commands_pilot_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(commands_pilot_TEST_DEPENDS )
set(commands_pilot_DOC_DEPENDS )
set(commands_pilot_URL_WEBSITE "")
set(commands_pilot_URL_BUGTRACKER "")
set(commands_pilot_URL_REPOSITORY "")
set(commands_pilot_DEPRECATED "")