set(_CATKIN_CURRENT_PACKAGE "follow_color")
set(follow_color_VERSION "0.0.0")
set(follow_color_MAINTAINER "alberto <alberto@todo.todo>")
set(follow_color_PACKAGE_FORMAT "2")
set(follow_color_BUILD_DEPENDS "cv_bridge" "gazebo_ros" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(follow_color_BUILD_EXPORT_DEPENDS "cv_bridge" "gazebo_ros" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(follow_color_BUILDTOOL_DEPENDS "catkin")
set(follow_color_BUILDTOOL_EXPORT_DEPENDS )
set(follow_color_EXEC_DEPENDS "cv_bridge" "gazebo_ros" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(follow_color_RUN_DEPENDS "cv_bridge" "gazebo_ros" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(follow_color_TEST_DEPENDS )
set(follow_color_DOC_DEPENDS )
set(follow_color_URL_WEBSITE "")
set(follow_color_URL_BUGTRACKER "")
set(follow_color_URL_REPOSITORY "")
set(follow_color_DEPRECATED "")