set(_CATKIN_CURRENT_PACKAGE "planning_trayectory")
set(planning_trayectory_VERSION "0.0.0")
set(planning_trayectory_MAINTAINER "alberto <alberto@todo.todo>")
set(planning_trayectory_PACKAGE_FORMAT "2")
set(planning_trayectory_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(planning_trayectory_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(planning_trayectory_BUILDTOOL_DEPENDS "catkin")
set(planning_trayectory_BUILDTOOL_EXPORT_DEPENDS )
set(planning_trayectory_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(planning_trayectory_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(planning_trayectory_TEST_DEPENDS )
set(planning_trayectory_DOC_DEPENDS )
set(planning_trayectory_URL_WEBSITE "")
set(planning_trayectory_URL_BUGTRACKER "")
set(planning_trayectory_URL_REPOSITORY "")
set(planning_trayectory_DEPRECATED "")