set(_CATKIN_CURRENT_PACKAGE "odometry_map")
set(odometry_map_VERSION "0.0.0")
set(odometry_map_MAINTAINER "alberto <alberto@todo.todo>")
set(odometry_map_PACKAGE_FORMAT "2")
set(odometry_map_BUILD_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(odometry_map_BUILD_EXPORT_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(odometry_map_BUILDTOOL_DEPENDS "catkin")
set(odometry_map_BUILDTOOL_EXPORT_DEPENDS )
set(odometry_map_EXEC_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(odometry_map_RUN_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(odometry_map_TEST_DEPENDS )
set(odometry_map_DOC_DEPENDS )
set(odometry_map_URL_WEBSITE "")
set(odometry_map_URL_BUGTRACKER "")
set(odometry_map_URL_REPOSITORY "")
set(odometry_map_DEPRECATED "")